version: '3.1'
services:
        mongo:
                image: mongo
                restart: always
                ports:
                        - 27017:27017
        mongo-express:
                image: mongo-express
                restart: always
                ports:
                        - 8081:8081
        db:
                image: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: 123456
                command:
                        --default-authentication-plugin=mysql_native_password
                        --character-set-server=utf8mb4
                        --collation-server=utf8mb4_general_ci
                        --explicit_defaults_for_timestamp=true
                        --lower_case_table_names=1
                        --max_allowed_packet=128M;
                ports:
                        - 3306:3306
                volumes:
                        - ./data:/var/lib/mysql
                             
        adminer:
                image: adminer
                restart: always
                ports:
                 - 8080:8080
        redis:
                image: redis
                restart: always
                ports:
                        - 6379:6379
        nginx:
                image: nginx
                restart: always
                ports:
                        - 8092:80
                volumes:
                        - ./nginx/conf.d/:/etc/nginx/conf.d
                        - ./frontend/dist:/var/www/html/
                        - ./static/:/static/